# Generated by Django 5.2 on 2025-07-01 18:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='is_direct',
            field=models.BooleanField(default=False, verbose_name='Client Direct'),
        ),
    ]
