# Generated by Django 5.2.4 on 2025-07-11 01:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='commande',
            name='code_commande',
            field=models.CharField(editable=False, max_length=20, unique=True),
        ),
    ]
