# Generated by Django 5.2 on 2025-07-23 00:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='lignecommandeclient',
            name='unique_ligne_commande',
        ),
    ]
