# Generated by Django 5.2 on 2025-07-02 00:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_client_is_direct'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='is_direct',
            field=models.BooleanField(default=False),
        ),
    ]
