# Generated by Django 5.2 on 2025-07-15 16:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_alter_commande_code_commande'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lignecommandeclient',
            name='produit',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.produit'),
        ),
    ]
