# Generated by Django 5.2 on 2025-07-09 01:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_alter_utilisateur_role'),
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='utilisateur',
            options={'permissions': [('manage_users', 'Peut gérer les utilisateurs'), ('reset_password', 'Peut réinitialiser les mots de passe'), ('change_role', 'Peut modifier les rôles')], 'verbose_name': 'Utilisateur', 'verbose_name_plural': 'Utilisateurs'},
        ),
        migrations.AddField(
            model_name='utilisateur',
            name='custom_permissions',
            field=models.ManyToManyField(blank=True, related_name='utilisateurs_custom', to='auth.permission', verbose_name='Permissions personnalisées'),
        ),
    ]
