# Generated by Django 5.2 on 2025-07-17 23:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_alter_commandeclient_tva'),
    ]

    operations = [
        migrations.AlterField(
            model_name='commandeclient',
            name='date_creation',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Date de création'),
        ),
    ]
