# Generated by Django 5.2 on 2025-07-23 15:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_remove_lignecommandeclient_unique_ligne_commande'),
    ]

    operations = [
        migrations.RenameField(
            model_name='rolechangelog',
            old_name='user',
            new_name='utilisateur',
        ),
        migrations.AddConstraint(
            model_name='lignecommandeclient',
            constraint=models.UniqueConstraint(fields=('commande', 'produit'), name='unique_produit_par_commande'),
        ),
    ]
