# Generated by Django 5.2 on 2025-07-18 02:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_alter_commandeclient_date_creation'),
    ]

    operations = [
        migrations.AddField(
            model_name='lignecommande',
            name='total_ligne_ht',
            field=models.DecimalField(decimal_places=2, default=0, editable=False, max_digits=10),
        ),
    ]
