# Generated by Django 5.2 on 2025-07-03 00:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_alter_client_is_direct'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='statistique',
            options={'ordering': ['-date'], 'verbose_name': 'Statistiques quotidiennes', 'verbose_name_plural': 'Statistiques quotidiennes'},
        ),
        migrations.AddField(
            model_name='statistique',
            name='produits_en_alerte',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='statistique',
            name='produits_en_rupture',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='statistique',
            name='total_mouvements_stock',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='statistique',
            name='total_utilisateurs_actifs',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='statistique',
            name='total_ventes',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='statistique',
            name='date',
            field=models.DateField(unique=True),
        ),
    ]
