# Generated by Django 5.2 on 2025-07-15 19:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_alter_lignecommandeclient_produit'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='commande',
            name='prix_total',
        ),
        migrations.RemoveField(
            model_name='commande',
            name='prix_unitaires',
        ),
        migrations.RemoveField(
            model_name='commande',
            name='quantite',
        ),
        migrations.AlterField(
            model_name='lignecommande',
            name='statut_livraison',
            field=models.CharField(choices=[('A_LIVRER', 'À livrer'), ('PARTIELLE', 'Livraison partielle'), ('LIVREE', 'Livrée')], default='A_LIVRER', max_length=20),
        ),
    ]
