# Generated by Django 5.2 on 2025-07-23 15:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_rename_user_rolechangelog_utilisateur_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='rolechangelog',
            old_name='utilisateur',
            new_name='user',
        ),
    ]
