# Generated by Django 5.2 on 2025-07-15 22:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_remove_commande_prix_total_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='produit',
            name='est_actif',
            field=models.BooleanField(default=True, verbose_name='Actif'),
        ),
    ]
