# Generated by Django 5.2 on 2025-07-03 00:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_alter_statistique_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='statistique',
            name='ca_commandes',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=15),
        ),
        migrations.AddField(
            model_name='statistique',
            name='ca_ventes_directes',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=15),
        ),
        migrations.AddField(
            model_name='statistique',
            name='commandes_clients',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='statistique',
            name='ventes_directes',
            field=models.IntegerField(default=0),
        ),
    ]
