# Generated by Django 5.2 on 2025-07-23 17:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_rename_utilisateur_rolechangelog_user'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='activitylog',
            options={'ordering': ['-timestamp'], 'verbose_name': "Log d'activité"},
        ),
        migrations.AlterModelOptions(
            name='statistique',
            options={'ordering': ['-date'], 'verbose_name': 'Statistique quotidienne'},
        ),
        migrations.AlterModelOptions(
            name='utilisateur',
            options={'permissions': [('manage_users', 'Peut gérer les utilisateurs'), ('reset_password', 'Peut réinitialiser les mots de passe'), ('change_role', 'Peut modifier les rôles')], 'verbose_name': 'Utilisateur'},
        ),
    ]
