# Generated by Django 5.2 on 2025-07-24 19:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_alter_activitylog_options_alter_statistique_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='client',
            name='siret',
        ),
    ]
