# Generated by Django 5.2 on 2025-07-18 14:10

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_alter_commande_utilisateur'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='stockproduit',
            name='emplacement',
        ),
        migrations.RemoveField(
            model_name='inventaire',
            name='responsable',
        ),
        migrations.RemoveField(
            model_name='ligneinventaire',
            name='inventaire',
        ),
        migrations.RemoveField(
            model_name='ligneinventaire',
            name='produit',
        ),
        migrations.RemoveField(
            model_name='lignevente',
            name='produit',
        ),
        migrations.RemoveField(
            model_name='lignevente',
            name='vente',
        ),
        migrations.RemoveField(
            model_name='parametres',
            name='tva_par_defaut',
        ),
        migrations.RemoveField(
            model_name='stockproduit',
            name='produit',
        ),
        migrations.RemoveField(
            model_name='vente',
            name='client',
        ),
        migrations.RemoveField(
            model_name='vente',
            name='tva',
        ),
        migrations.RemoveField(
            model_name='vente',
            name='utilisateur',
        ),
        migrations.AlterField(
            model_name='commandeclient',
            name='utilisateur',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='commandes_client', to=settings.AUTH_USER_MODEL),
        ),
        migrations.DeleteModel(
            name='Emplacement',
        ),
        migrations.DeleteModel(
            name='Inventaire',
        ),
        migrations.DeleteModel(
            name='LigneInventaire',
        ),
        migrations.DeleteModel(
            name='LigneVente',
        ),
        migrations.DeleteModel(
            name='Parametres',
        ),
        migrations.DeleteModel(
            name='StockProduit',
        ),
        migrations.DeleteModel(
            name='Vente',
        ),
    ]
