# Generated by Django 5.2 on 2025-07-03 00:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_statistique_ca_commandes_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='statistique',
            name='commandes_clients',
        ),
        migrations.RemoveField(
            model_name='statistique',
            name='ventes_directes',
        ),
        migrations.AddField(
            model_name='statistique',
            name='date_mise_a_jour',
            field=models.DateTimeField(auto_now=True, verbose_name='Dernière mise à jour'),
        ),
        migrations.AlterField(
            model_name='statistique',
            name='ca_commandes',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=15, verbose_name='CA HT commandes clients'),
        ),
        migrations.AlterField(
            model_name='statistique',
            name='ca_ht',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=15, verbose_name="Chiffre d'affaires HT total"),
        ),
        migrations.AlterField(
            model_name='statistique',
            name='ca_ventes_directes',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=15, verbose_name='CA HT ventes directes'),
        ),
        migrations.AlterField(
            model_name='statistique',
            name='date',
            field=models.DateField(unique=True, verbose_name='Date des statistiques'),
        ),
        migrations.AlterField(
            model_name='statistique',
            name='produits_en_alerte',
            field=models.IntegerField(default=0, verbose_name="Produits sous seuil d'alerte"),
        ),
        migrations.AlterField(
            model_name='statistique',
            name='produits_en_rupture',
            field=models.IntegerField(default=0, verbose_name='Produits en rupture'),
        ),
        migrations.AlterField(
            model_name='statistique',
            name='total_clients',
            field=models.IntegerField(default=0, verbose_name='Nouveaux clients'),
        ),
        migrations.AlterField(
            model_name='statistique',
            name='total_commandes',
            field=models.IntegerField(default=0, verbose_name='Total des commandes fournisseurs'),
        ),
        migrations.AlterField(
            model_name='statistique',
            name='total_fournisseurs',
            field=models.IntegerField(default=0, verbose_name='Nouveaux fournisseurs'),
        ),
        migrations.AlterField(
            model_name='statistique',
            name='total_mouvements_stock',
            field=models.IntegerField(default=0, verbose_name='Mouvements de stock'),
        ),
        migrations.AlterField(
            model_name='statistique',
            name='total_produits',
            field=models.IntegerField(default=0, verbose_name='Produits actifs'),
        ),
        migrations.AlterField(
            model_name='statistique',
            name='total_utilisateurs_actifs',
            field=models.IntegerField(default=0, verbose_name='Utilisateurs actifs'),
        ),
        migrations.AlterField(
            model_name='statistique',
            name='total_ventes',
            field=models.IntegerField(default=0, verbose_name='Total des ventes clients'),
        ),
        migrations.AddIndex(
            model_name='statistique',
            index=models.Index(fields=['date'], name='api_statist_date_0fe328_idx'),
        ),
        migrations.AddIndex(
            model_name='statistique',
            index=models.Index(fields=['ca_ht'], name='api_statist_ca_ht_090282_idx'),
        ),
    ]
