# Generated by Django 5.2 on 2025-07-20 12:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_remove_stockproduit_emplacement_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='utilisateur',
            name='est_actif',
        ),
        migrations.AlterField(
            model_name='utilisateur',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
