# Generated by Django 5.2 on 2025-07-03 01:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_remove_statistique_commandes_clients_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='statistique',
            options={'ordering': ['-date'], 'verbose_name': 'Statistique quotidienne', 'verbose_name_plural': 'Statistiques quotidiennes'},
        ),
        migrations.RemoveIndex(
            model_name='statistique',
            name='api_statist_date_0fe328_idx',
        ),
        migrations.RemoveIndex(
            model_name='statistique',
            name='api_statist_ca_ht_090282_idx',
        ),
        migrations.RemoveField(
            model_name='statistique',
            name='ca_commandes',
        ),
        migrations.RemoveField(
            model_name='statistique',
            name='ca_ht',
        ),
        migrations.RemoveField(
            model_name='statistique',
            name='ca_ventes_directes',
        ),
        migrations.RemoveField(
            model_name='statistique',
            name='date_mise_a_jour',
        ),
        migrations.RemoveField(
            model_name='statistique',
            name='produits_en_alerte',
        ),
        migrations.RemoveField(
            model_name='statistique',
            name='produits_en_rupture',
        ),
        migrations.RemoveField(
            model_name='statistique',
            name='total_clients',
        ),
        migrations.RemoveField(
            model_name='statistique',
            name='total_commandes',
        ),
        migrations.RemoveField(
            model_name='statistique',
            name='total_fournisseurs',
        ),
        migrations.RemoveField(
            model_name='statistique',
            name='total_mouvements_stock',
        ),
        migrations.RemoveField(
            model_name='statistique',
            name='total_produits',
        ),
        migrations.RemoveField(
            model_name='statistique',
            name='total_utilisateurs_actifs',
        ),
        migrations.RemoveField(
            model_name='statistique',
            name='total_ventes',
        ),
        migrations.AddField(
            model_name='statistique',
            name='montant_commandes',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=15),
        ),
        migrations.AddField(
            model_name='statistique',
            name='montant_total',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=15),
        ),
        migrations.AddField(
            model_name='statistique',
            name='montant_ventes_directes',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=15),
        ),
        migrations.AddField(
            model_name='statistique',
            name='mouvements_stock',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='statistique',
            name='nb_commandes',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='statistique',
            name='nb_commandes_clients',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='statistique',
            name='nb_ventes',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='statistique',
            name='nb_ventes_directes',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='statistique',
            name='nouveaux_clients',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='statistique',
            name='nouveaux_fournisseurs',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='statistique',
            name='produits_actifs',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='statistique',
            name='produits_alerte',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='statistique',
            name='produits_rupture',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='statistique',
            name='utilisateurs_actifs',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='statistique',
            name='date',
            field=models.DateField(unique=True),
        ),
    ]
