# Generated by Django 5.2 on 2025-07-20 13:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_remove_utilisateur_est_actif_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='commandeclient',
            name='statut',
            field=models.CharField(choices=[('VALIDEE', 'Validée par le client')], default='Validée par le client', max_length=20),
        ),
    ]
